dbConfig:
    dbConfigFile: testnet/plutus-pab.db
    dbConfigPoolSize: 20

pabWebserverConfig:
  baseUrl: http://localhost:9080
  staticDir: plutus-pab-client/dist
  permissiveCorsPolicy: False
  # Optional timeout (in seconds) for calls to endpoints that are not currently
  # available. If this is not set, calls to unavailable endpoints fail
  # immediately.
  endpointTimeout: 5

walletServerConfig:
  tag: LocalWalletConfig
  walletSettings:
    baseUrl: http://localhost:8090

nodeServerConfig:
  pscSocketPath: testnet/node.sock
  pscBaseUrl: "localhost"
  pscKeptBlocks: 2160
  pscNetworkId: "1097911063" # Testnet network ID (main net = empty string)
  pscSlotConfig:
    scSlotZeroTime: 1596059091000 # Wednesday, July 29, 2020 21:44:51 - shelley launch time in milliseconds
    scSlotLength: 1000 # In milliseconds
  pscFeeConfig:
    fcConstantFee:
      getLovelace: 10 # Constant fee per transaction in lovelace
    fcScriptsFeeFactor: 1.0 # Factor by which to multiply size-dependent scripts fee in lovelace
  pscInitialTxWallets: []
  pscNodeMode: AlonzoNode

chainIndexConfig:
  ciBaseUrl: http://localhost:9083
  ciWatchedAddresses: []

requestProcessingConfig:
  requestProcessingInterval: 1

signingProcessConfig:
  spBaseUrl: http://localhost:9084
  spWallet:
    getWallet:
      getWalletId: 7cc75497535877261173ab585f5abb431f7ba484

metadataServerConfig:
  mdBaseUrl: http://localhost:9085

developmentOptions:
  pabRollbackHistory: 1
  pabResumeFrom:
    # "tag" : "PointAtGenesis" }
      { "tag" : "Point"
      , "pointBlockId" : "0ab537b87193a64fb6fd1e5bc20a3298ec0fa91f6f43ea22060598335aa11890"
      , "pointSlot" : {"getSlot" : 51197568}
      }
